/* tslint:disable */
/* eslint-disable */
/**
 * Rhyme API v1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 *
 *
 * @export
 * @interface IRhyme
 */
export interface IRhyme {

    /**
     * @type {number}
     * @memberof IRhyme
     */
    id?: number;

    /**
     * @type {string}
     * @memberof IRhyme
     */
    title?: string;

    /**
     * @type {string}
     * @memberof IRhyme
     */
    author?: string;

    /**
     * @type {string}
     * @memberof IRhyme
     */
    content?: string;

    /**
     * @type {string}
     * @memberof IRhyme
     */
    date?: string;

    /**
     * @type {boolean}
     * @memberof IRhyme
     */
    flagDeleted?: boolean;
}
